export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const STORE_ACCESS_TOKEN = 'STORE_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';